name: Workflow Filter

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "*/10 * * * *"
  push:
    branches:
      - main
      - '!feature/*'
    #branches-ignore:
    #  - feature/*
    #  - test/*
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo ${{ github.event_name }}
        run: echo this workflow/job/step is executed for event type = ${{ github.event_name }}